### PR TITLE
Add option to change font

### PR DESCRIPTION
**Pull request by UtkarshMe**
Adresses #40 

Problems:
- The default font button shows ```none 0```
- Unable to change only the font size

### CODE REVIEW

**Comment by Philip-Scott** [comment]
Hey! nice job 

The default font shows `none 0` due to the fact that it's grabbing it from the system's Monospace font. You might need to grab it also from there :wink: Just make sure that the terminal's font settings remains clear if there are no changes

_Hint: See the Fonts panel for how to get the mono font_

**Comment by UtkarshMe** [comment]
Everything works fine except this:
- Updating system monospace font does not show up in terminal pane until switchboard is restarted.

**Comment by Philip-Scott** [comment]
Hmm... you could just connect to the system font settings and update the font here if the user hasn't set it

**Comment by UtkarshMe** [comment]
Ok, I tried that but it didn't work. Maybe the UI is built only once(?). I tried tracking down how the reset button works but couldn't. Need help!

**Comment by Philip-Scott** [comment]
Yeah, the UI is only built once. But you should be able to connect to the property change signal of the SystemFontSettings with something like this: https://wiki.gnome.org/Projects/Vala/PropertiesSample to this class: https://github.com/elementary-tweaks/elementary-tweaks/blob/master/src/Settings/GnomeSettings.vala#L55



This is what the reset button calls: https://github.com/elementary-tweaks/elementary-tweaks/blob/master/src/Settings/TerminalSettings.vala#L47

**Comment by UtkarshMe** [comment]
Ok, I've gotten this far:

- The files in Settings are responsible for sending data when requested.
- The files in Panes are responsible for UI
- The change is reflected in the UI only when init_data() is called
- init_data() can't be called by any other Pane file

What I can't figure out is:
- How to call init_data() of TerminalPane when a member of FontsPane is changes
- Any other way to update TerminalPane (bypassing init_data?)

**Pull request closed without merging**
