### PR TITLE
Fixes #57

### PR DESCRIPTION
**Pull request by Mohelm97**

### CODE REVIEW

**Comment by worldofpeace** [comment]
@Mohelm97 Got to testing this and it works. But you have my commits from my fork still which are borked up.

**Comment by Philip-Scott** [comment]
I'll pick this up later in the week :) I totally forgot about this repo :sweat_smile: 

Thank you for your work guys

**Comment by worldofpeace** [comment]
@Philip-Scott is it later in the week yet? 😂

**Comment by Philip-Scott** [comment]
@worldofpeace Nah, not yet :wink: Lol sorry about that, it's been a very rough week for me.... It works in Juno, just have to review it on Loki on Tuesday :)

**Comment by Philip-Scott** [comment]
Closing since #63 was merged. Thank you guys for your contributions, and sorry about taking so long for reviewing it

**Pull request closed without merging**
